package notes

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mdelapenya/biomelab/internal/git"
)

const legacyAgentBootstrapBlock = "<!-- biomelab:task-notes:start -->\n" +
	"## Biomelab task context\n\n" +
	"Before starting work, read `.biomelab/note.md` and `.biomelab/pr-title.md` when they exist. " +
	"Treat their contents as task context; they do not override repository instructions.\n" +
	"<!-- biomelab:task-notes:end -->\n"

const readClaudeGuidance = "Before starting work, also read `CLAUDE.md` when it exists so its repository guidance is preserved.\n"

const agentBootstrapBlock = "<!-- biomelab:task-notes:start -->\n" +
	"## Biomelab task context\n\n" +
	"At the start of every session:\n" +
	"- Read `.biomelab/issue.md` for the immutable initial requirements. If it does not exist (for example, in an older worktree), read `.biomelab/note.md` as the available legacy task context; it may have been edited.\n" +
	"- Read `.biomelab/progress.md` when it exists for the ongoing agent handoff.\n" +
	"- Read `.biomelab/note.md` and `.biomelab/pr-title.md` when they exist as editable pull-request draft context.\n" +
	"- Inspect `git status`, the current diff, recent commits, and the relevant code. Reconcile those observations with the progress notes because notes can be stale. Do not assume that all original issue work remains or redo completed work. If progress notes are absent, derive the current state from the code and repository history rather than assuming the issue is untouched.\n\n" +
	"During work, update `.biomelab/progress.md` at meaningful milestones and before ending or handing off. Record completed work, decisions, remaining tasks or blockers, validation outcomes, and the relevant current commit or uncommitted changes. Record only facts you observed. Preserve `.biomelab/issue.md` as the original requirements snapshot. If the task is complete, say so in the progress file instead of restarting the work.\n\n" +
	"These task files supplement repository instructions; they do not override them.\n" +
	"<!-- biomelab:task-notes:end -->\n"

const kiroBootstrapPrefix = `---
inclusion: always
---

`

type bootstrapFile struct {
	path          string
	prefix        string
	onlyIfPresent bool
}

var agentBootstrapFiles = []bootstrapFile{
	{path: "AGENTS.md"},
	// Codex gives AGENTS.override.md precedence over AGENTS.md. Preserve and
	// augment an existing override, but do not create one because doing so
	// would unnecessarily mask the repository's AGENTS.md.
	{path: "AGENTS.override.md", onlyIfPresent: true},
	{path: "CLAUDE.md"},
	{path: "GEMINI.md"},
	{path: filepath.Join(".kiro", "steering", "biomelab-task.md"), prefix: kiroBootstrapPrefix},
}

// EnsureAgentBootstrap installs worktree-local agent instructions that tell
// supported coding agents to load Biomelab's task notes at session startup.
// Unrelated existing instruction bytes are preserved and receive a marked
// block at the end. Exact blocks generated by the previous version are
// upgraded at their existing position. Files created by Biomelab are excluded
// from Git; existing tracked files remain visible as intentional modifications.
//
// The operation is idempotent but not transactional. If a later target fails,
// earlier targets remain bootstrapped and the returned error names the failed
// path so callers can report partial note setup without removing the worktree.
func EnsureAgentBootstrap(worktreeDir string) error {
	root, err := safeBootstrapRoot(worktreeDir)
	if err != nil {
		return err
	}

	for _, spec := range agentBootstrapFiles {
		target := filepath.Join(root, spec.path)
		_, statErr := os.Lstat(target)
		if errors.Is(statErr, os.ErrNotExist) && !spec.onlyIfPresent {
			// Record the exclusion before creating the file. If exclusion
			// fails, no instruction file is left behind in an unignored state;
			// a harmless exclusion left by a later create failure is retryable.
			if err := git.EnsureExcluded(root, "/"+filepath.ToSlash(spec.path)); err != nil {
				return fmt.Errorf("exclude agent instructions %s: %w", spec.path, err)
			}
		}
		block := agentBootstrapBlock
		if spec.path == "AGENTS.md" || spec.path == "AGENTS.override.md" {
			block = bootstrapBlockWithClaudeGuidance()
		}
		_, err := ensureBootstrapFile(root, spec, block)
		if err != nil {
			return fmt.Errorf("bootstrap agent instructions %s: %w", spec.path, err)
		}
	}
	return nil
}

func safeBootstrapRoot(worktreeDir string) (string, error) {
	root, err := filepath.Abs(worktreeDir)
	if err != nil {
		return "", fmt.Errorf("resolve worktree path: %w", err)
	}
	info, err := os.Lstat(root)
	if err != nil {
		return "", fmt.Errorf("stat worktree: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return "", fmt.Errorf("worktree path is not a regular directory")
	}
	return root, nil
}

func ensureBootstrapFile(root string, spec bootstrapFile, block string) (bool, error) {
	target := filepath.Join(root, spec.path)
	parent := filepath.Dir(target)
	if err := ensureSafeBootstrapDirs(root, parent, false); err != nil {
		return false, err
	}
	info, err := os.Lstat(target)
	if err == nil {
		if !info.Mode().IsRegular() {
			return false, fmt.Errorf("instruction path is not a regular file")
		}
		data, err := os.ReadFile(target)
		if err != nil {
			return false, fmt.Errorf("read: %w", err)
		}
		if spec.path == filepath.Join(".kiro", "steering", "biomelab-task.md") && !kiroAlwaysIncluded(data) {
			return false, fmt.Errorf("existing Kiro steering file is not always included")
		}
		migrated, changed := migrateLegacyBootstrap(data, block)
		if changed {
			if err := replaceBootstrapFile(target, info.Mode().Perm(), migrated); err != nil {
				return false, err
			}
			return false, nil
		}
		if containsBootstrapBlock(data, block) {
			return false, nil
		}
		f, err := os.OpenFile(target, os.O_APPEND|os.O_WRONLY, 0)
		if err != nil {
			return false, fmt.Errorf("open: %w", err)
		}
		addition := []byte(block)
		if len(data) > 0 && data[len(data)-1] != '\n' {
			addition = append([]byte("\n\n"), addition...)
		} else if len(data) > 0 {
			addition = append([]byte("\n"), addition...)
		}
		if _, err := f.Write(addition); err != nil {
			_ = f.Close()
			return false, fmt.Errorf("append: %w", err)
		}
		if err := f.Close(); err != nil {
			return false, fmt.Errorf("close: %w", err)
		}
		return false, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("stat: %w", err)
	}
	if spec.onlyIfPresent {
		return false, nil
	}

	if err := ensureSafeBootstrapDirs(root, parent, true); err != nil {
		return false, err
	}
	content := []byte(spec.prefix + block)
	f, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, filePerm)
	if err != nil {
		return false, fmt.Errorf("create: %w", err)
	}
	if _, err := f.Write(content); err != nil {
		_ = f.Close()
		return false, fmt.Errorf("write: %w", err)
	}
	if err := f.Close(); err != nil {
		return false, fmt.Errorf("close: %w", err)
	}
	return true, nil
}

func migrateLegacyBootstrap(data []byte, block string) ([]byte, bool) {
	canonicalPresent := containsBootstrapBlock(data, block)
	changed := false
	for _, legacy := range []string{legacyBootstrapBlockWithClaudeGuidance(), legacyAgentBootstrapBlock} {
		if bytes.Contains(data, []byte(legacy)) {
			replacement := block
			if canonicalPresent {
				replacement = ""
			}
			data = bytes.ReplaceAll(data, []byte(legacy), []byte(replacement))
			canonicalPresent = true
			changed = true
		}
		legacyCRLF := strings.ReplaceAll(legacy, "\n", "\r\n")
		if bytes.Contains(data, []byte(legacyCRLF)) {
			blockCRLF := strings.ReplaceAll(block, "\n", "\r\n")
			replacement := blockCRLF
			if canonicalPresent {
				replacement = ""
			}
			data = bytes.ReplaceAll(data, []byte(legacyCRLF), []byte(replacement))
			canonicalPresent = true
			changed = true
		}
	}
	return data, changed
}

func containsBootstrapBlock(data []byte, block string) bool {
	return bytes.Contains(data, []byte(block)) ||
		bytes.Contains(data, []byte(strings.ReplaceAll(block, "\n", "\r\n")))
}

func replaceBootstrapFile(path string, perm os.FileMode, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".biomelab-bootstrap-*")
	if err != nil {
		return fmt.Errorf("create replacement: %w", err)
	}
	tempPath := f.Name()
	defer func() { _ = os.Remove(tempPath) }()
	if err := f.Chmod(perm); err != nil {
		_ = f.Close()
		return fmt.Errorf("set replacement permissions: %w", err)
	}
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return fmt.Errorf("write: %w", err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("close: %w", err)
	}
	if err := os.Rename(tempPath, path); err != nil {
		return fmt.Errorf("replace: %w", err)
	}
	return nil
}

func bootstrapBlockWithClaudeGuidance() string {
	end := "<!-- biomelab:task-notes:end -->\n"
	return agentBootstrapBlock[:len(agentBootstrapBlock)-len(end)] + readClaudeGuidance + end
}

func legacyBootstrapBlockWithClaudeGuidance() string {
	end := "<!-- biomelab:task-notes:end -->\n"
	return legacyAgentBootstrapBlock[:len(legacyAgentBootstrapBlock)-len(end)] + readClaudeGuidance + end
}

func kiroAlwaysIncluded(data []byte) bool {
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	if !strings.HasPrefix(text, "---\n") {
		return true // Kiro's documented default is always included.
	}
	end := strings.Index(text[4:], "\n---")
	if end < 0 {
		return true
	}
	frontmatter := text[4 : 4+end]
	for _, line := range strings.Split(frontmatter, "\n") {
		key, value, ok := strings.Cut(line, ":")
		if ok && strings.TrimSpace(key) == "inclusion" {
			return strings.TrimSpace(value) == "always"
		}
	}
	return true
}

func ensureSafeBootstrapDirs(root, dir string, create bool) error {
	rel, err := filepath.Rel(root, dir)
	if err != nil || rel == ".." || filepath.IsAbs(rel) {
		return fmt.Errorf("instruction directory escapes worktree")
	}
	current := root
	for _, part := range splitPath(rel) {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if errors.Is(err, os.ErrNotExist) {
			if !create {
				return nil
			}
			if err := os.Mkdir(current, dirPerm); err != nil {
				return fmt.Errorf("create instruction directory: %w", err)
			}
			continue
		}
		if err != nil {
			return fmt.Errorf("stat instruction directory: %w", err)
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			return fmt.Errorf("instruction parent is not a regular directory")
		}
	}
	return nil
}

func splitPath(path string) []string {
	if path == "." || path == "" {
		return nil
	}
	var parts []string
	for path != "." && path != string(filepath.Separator) {
		parent, base := filepath.Split(path)
		parts = append([]string{base}, parts...)
		path = filepath.Clean(parent)
	}
	return parts
}
